### ISSUE TITLE
can't split ':' values

### ISSUE THREAD

**Issue by spowww** [RustySnek/librus-apix#20]
Hi
Looks like the API was changes for in the more complexes example I've got grades problem reading using example scripts

Traceback (most recent call last):
  File "/home/pg/apps/librus-apix/ania/grades_example.py", line 12, in <module>
    grades, semester_grades = get_grades(token, sort_by[0])
  File "/home/pg/apps/librus-apix/librus_apix/grades.py", line 95, in get_grades
    key, value = attr.split(': ')
ValueError: too many values to unpack (expected 2)

for the other kid looks pretty ok
Subject: Etyka
Subject: Język angielski
	|6| - 2023-10-27
	|5| - 2023-11-12
Subject: Religia
etc.
![grades_issue](https://github.com/RustySnek/librus-apix/assets/82202909/6c1144e4-d4e4-4868-ae26-554d988f3515)

Hope that could help for the future software usage
thanks a lot

**Comment by RustySnek** [comment]
Hey, it looks like the issue is caused by one of attributes for example category having ":" in them. I haven't really accounted for that in my code, I've fixed it, pull the changes and let me know if it works now.

**Comment by spowww** [comment]
Changes fixed existing issue
now both account are able to get the dates
Subject: Matematyka
	|5| - 2023-09-13
	|5| - 2023-09-22
	|3| - 2023-10-20
Subject: Muzyka
	|+| - 2023-10-09
	|+| - 2023-10-09
	|6| - 2023-10-30
Subject: Plastyka
	|+| - 2023-09-12
	|5| - 2023-10-05
Subject: Przyroda
	|+| - 2023-09-20
	|6| - 2023-10-09
	|6| - 2023-10-30

thanks a lot for such quick bug fixing
