### ISSUE TITLE
`message.title` does not return the full title

### ISSUE THREAD

**Issue by docentYT** [RustySnek/librus-apix#46]
`message.title` returns the title displayed in the message list, not when the message is accessed. If the title is long then it ends with '...'.

**Comment by RustySnek** [comment]
This is the intended behavior, getting full title would require requesting each and every message one by one.
All tho now that you mention it, I never added a way to get full title in message_content function.
Will fix soon tm

**Comment by RustySnek** [comment]
I've changed the message_content function to now return MessageData  which includes full title #47 
```py
@dataclass
class MessageData:
    author: str
    title: str
    content: str
    date: str
```
